### ISSUE TITLE
Can't find this plane in FlightGear after install

### ISSUE THREAD

**Issue by sidi762** [FGMEMBERS/767#1]

**Comment by JWocky** [comment]
Launcher failure ... the launcher doesn't show planes with an include to another folder in the property-list. FG works fine with it, it's only the launcher. You need to use a third party launcher, those work, for example FGo! or start her form a terminal.

**Comment by sidi762** [comment]
@JWocky When i tried to launch it from terminal, it says can't open "Aircraft/JPack/Interface.xml"

**Comment by IAHM-COL** [comment]
Need to also install this aircraft:

https://github.com/FGMEMBERS/JPack

**Comment by sidi762** [comment]
@JWocky Thank you!

**Comment by rx4** [comment]
Thanks.
